config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard'

  resources :alibis do
    resources :bookings, only: %i[create]
    member do
      patch :archive
    end
  end

  resources :bookings, only: %i[] do
    member do
      patch :accept
      patch :decline
      patch :cancel
    end
  end

  resources :users, only: %i[show]
end

app/models/alibi.rb
class Alibi < ApplicationRecord
  CATEGORIES = %w[family date journey speak cinema].freeze

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  include PgSearch::Model

  pg_search_scope :search_by_category_title_and_content,
                  against: {
                    category: "A",
                    title: "C",
                    content: "D"
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  enum :status, { available: 0, archived: 1 }, default: :available
  enum :goal, { ask: 0, offer: 1 }, default: :ask
  enum :reservation_type, { solo: 0, multi: 1 }, default: :solo

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :content, presence: true, length: { minimum: 10 }
  validates :status, inclusion: { in: statuses.keys }
  validates :category, inclusion: { in: CATEGORIES }
  validates :date, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :user, presence: true
  validates :goal, inclusion: { in: goals.keys }
  validates :reservation_type, inclusion: { in: reservation_types.keys }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :alibi

  enum :status, { pending: 0, approved: 1, declined: 2, cancelled: 3 }, default: :pending
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :alibis

  has_one_attached :photo
end

app/controllers/alibis_controller.rb
class AlibisController < ApplicationController
  before_action :set_alibi, only: %i[show edit update archive]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @alibis = Alibi.search_by_category_title_and_content(params[:query])
    else
      @alibis = Alibi.all
    end
  end

  def show
    @alibi = Alibi.find(params[:id])
    @booking = Booking.new
  end

  def new
    @alibi = Alibi.new
  end

  def create
    @alibi = Alibi.new(alibi_params)
    @alibi.user = current_user
    @alibi.available!
    if @alibi.save
      redirect_to alibi_path(@alibi), notice: "Alibi was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def archive
    if @alibi.archived!
      redirect_to alibis_path, notice: 'Alibi has been successfully archived.'
    else
      redirect_to alibi_path(@alibi), alert: 'Error archiving alibi.'
    end
  end

  def edit; end

  def update
    if @alibi.update(alibi_params)
      redirect_to alibi_path(@alibi), notice: "Alibi was successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def alibi_params
    params.require(:alibi).permit(:title, :content, :status, :category, :date, :price, :photo, :goal)
  end

  def set_alibi
    @alibi = Alibi.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit accept decline cancel]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.status = :pending
    @booking.alibi = Alibi.find(params[:alibi_id])
    @booking.user = current_user
    if @booking.save
      redirect_to @booking.alibi
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def accept
    @alibi = @booking.alibi
    if @booking.update(status: :approved)
      redirect_to alibi_path(@alibi), notice: 'Booking has been successfully accepted.'
    else
      redirect_to alibi_path(@alibi), alert: 'Error accepting booking.'
    end
  end

  def decline
    @alibi = @booking.alibi
    if @booking.update(status: :declined)
      redirect_to alibi_path(@alibi), notice: 'Booking has been successfully declined.'
    else
      redirect_to alibi_path(@alibi), alert: 'Error declining booking.'
    end
  end

  def cancel
    @alibi = @booking.alibi
    if @booking.update(status: :cancelled)
      redirect_to alibi_path(@alibi), notice: 'Booking has been successfully cancelled.'
    else
      redirect_to alibi_path(@alibi), alert: 'Error cancelling booking.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home; end

  def dashboard
    @alibis = current_user.alibis
    @bookings = current_user.bookings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alibis/edit.html.erb
<div class="container my-3">
  <%= simple_form_for(@alibi) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <fieldset <%= 'disabled' if @alibi.archived? %>>
      <div class="form-inputs">
        <%= f.input :title, required: true %>
        <%= f.input :content, as: :text, required: true %>
        <%= f.input :photo, as: :file %>
        <%= f.input :category, collection: Alibi::CATEGORIES, include_blank: false %>
        <%= f.input :date,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
        <%= f.input :goal, collection: Alibi.goals.keys, include_blank: false %>
        <%= f.input :reservation_type, collection: Alibi.reservation_types.keys, include_blank: false %>
        <%= f.input :price, required: true, input_html: { value: @alibi.price || 1, min: 0 } %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, 'Update Alibi', class: 'btn btn-primary' %>
      </div>
    </fieldset>
  <% end %>

  <% if @alibi.available? %>
    <%= button_to 'Archive', archive_alibi_path(@alibi), method: :patch, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure you want to archive this alibi?' } %>
  <% end %>
</div>

app/views/alibis/index.html.erb
<div class="container mt-3">
  <% if @alibis.where(status: 'available').empty? %>
  <div class="text-center mt-5">
    <p class="my-5">No alibi available yet for <strong><%= params[:query] %></strong>.</p>
    <%= link_to 'Back to Home page', root_path, class: 'btn btn-outline-dark' %>
    <% end %>
  </div>
  <div class="cards d-flex flex-wrap gap-3 justify-content-center mt-5">
    <% @alibis.where(status: 'available').reverse.each do |alibi| %>
      <div class="card col-3" style="width: 18rem; height: auto;">
        <% image = (alibi.photo.attached? ? alibi.photo : "#{alibi.category}.jpg") %>
        <%= image_tag(image, class: "card-img-top h-50 object-fit-cover", alt: "Alt de mon alibi") %>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title"><%= alibi.title %></h5>
          <div class="d-flex justify-content-around mt-2">
            <span class="badge bg-primary fw-normal"><%= alibi.category.capitalize %></span>
            <span class="badge bg-warning fw-normal"><%= alibi.price %>€</span>
          </div>
          <div class="d-flex justify-content-around mt-2">
            <p class="mb-0"><small><%= alibi.date.strftime("%Y/%m/%d - %H:%M") %></small></p>
          </div>
          <div class="d-flex justify-content-center mt-auto">
            <%= link_to "See details", alibi_path(alibi), class: "btn btn-primary"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/alibis/new.html.erb
<div class="container my-3">
  <%= simple_form_for(@alibi) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title, required: true %>
      <%= f.input :content, as: :text, required: true %>
      <%= f.input :photo, as: :file %>
      <%= f.input :category, collection: Alibi::CATEGORIES, include_blank: false %>
      <%= f.input :date,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :goal, collection: Alibi.goals.keys, include_blank: false %>
      <%= f.input :reservation_type, collection: Alibi.reservation_types.keys, include_blank: false %>
      <%= f.input :price, required: true, input_html: { value: @alibi.price || 1, min: 0 } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Create Alibi', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/alibis/show.html.erb
<div class="container my-3">
  <div class="card-wrapper d-flex bg-white rounded-5 img-container shadow overflow-hidden">
    <% if @alibi.photo.attached? %>
      <%= cl_image_tag @alibi.photo.key %>
    <% else %>
      <%= image_tag("#{@alibi.category}.jpg", class:"rounded-start-5 object-fit-cover", alt: "Alt de mon alibi") %>
    <% end %>
    <div class="Card">
      <% avatar = (@alibi.user.photo.attached? ? @alibi.user.photo : "avatar.png") %>
      <%= image_tag avatar, class: "avatar-bordered dropdown-toggle w-25", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div><strong>By</strong> <%=@alibi.user.email %></div>
      <div>
        <h3 class="card-title mb-5"><%= @alibi.title %></h3>
        <p class="card-text"><%= @alibi.content %></p>
      </div>
      <div class="Date gap-1">
        <div><strong>Category:</strong> <%= @alibi.category.capitalize %></div>
        <div><strong>Date:</strong> <%= @alibi.date.strftime("%Y/%m/%d - %H:%M") %></div>
        <div><strong>Price:</strong> <%= number_to_currency(@alibi.price, delimiter: ' ', format: "%n %u", precision: 0, unit: '€') %></div>
      </div>

      <% if current_user %>
        <div class='align-items-center d-flex flex-column gap-4'>
          <% if current_user != @alibi.user %>
            <% if @alibi.bookings.where(user_id: current_user).exists? %>
              <button class='align-self-center btn btn-primary disabled px-5'>Already booked</button>
            <% else %>
              <%= simple_form_for [@alibi, @booking] do |f| %>
                <%= f.button :submit, 'Book this alibi', class: 'align-self-center btn btn-outline-primary px-5' %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to "Edit this alibi", edit_alibi_path(@alibi), class: 'btn btn-outline-primary px-5' %>
            <%= button_to 'Archive this alibi', archive_alibi_path(@alibi), method: :patch, class: 'btn btn-outline-danger px-5', data: { confirm: 'Are you sure you want to archive this alibi?' } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

    <div class="bookings">
      <% if current_user && current_user == @alibi.user %>
        <h3 class="mt-5">Bookings for my alibi</h3>
        <% if @alibi.bookings.empty? %>
          <p>No booking yet.</p>
        <% end %>

        <% @alibi.bookings.reverse.each do |booking| %>
          <div class="notification">
            <% avatar = (booking.user.photo.attached? ? booking.user.photo : "avatar.png") %>
            <%= image_tag avatar, class: "avatar-large me-3" %>
            <div class="notification-content">
              <p><small><%= booking.created_at.strftime("%Y/%m/%d - %H:%M") %></small></p>
              <p><%= booking.user.email %></p>
            </div>

            <div class="notification-actions">
              <div class="d-flex gap-3">
                <% case %>
                  <% when booking.pending? %>
                    <%= button_to 'Accept', accept_booking_path(booking), method: :patch, class: 'btn btn-outline-success' %>
                    <%= button_to 'Decline', decline_booking_path(booking), method: :patch, class: 'btn btn-outline-danger' %>
                  <% when booking.approved? %>
                    <button class='btn btn-success disabled'>Accepted</button>
                    <%= button_to 'Cancel', cancel_booking_path(booking), method: :patch, class: 'btn btn-outline-dark' %>
                  <% when booking.declined? %>
                    <button class='btn btn-danger disabled'>Declined</button>
                  <% when booking.cancelled? %>
                    <button class='btn btn-dark disabled'>Cancelled</button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alibis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="flex-grow-1">
      <%= yield %>
    </div>
  </body>
  <div class="footer bg-white mt-5">
    <div class="footer-links">
      <a href="https://github.com/lewagon" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://instagram.com/lewagonfrance?igshid=OGQ5ZDc2ODk2ZA==" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/lewagon/?locale=fr_FR" target="_blank"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/Lewagonparis" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="https://fr.linkedin.com/showcase/lewagonfrance/" target="_blank"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      ©Alibis.com Made by The mango's members 🥭 at Le Wagon
    </div>
  </div>
  <script src="https://unpkg.com/flatpickr@4.6.9/dist/plugins/scrollPlugin.js"></script>
</html>

app/views/pages/dashboard.html.erb
<div class="container my-3">
  <div>
    <h2>My alibis</h2>
    <% @alibis.reverse.each do |alibi| %>
      <div class="notification">
        <div class="notification-content">
          <p><small><%= alibi.created_at.strftime("%Y/%m/%d - %H:%M") %></small></p>
          <% if alibi.archived? %>
            <%= link_to alibi.title, "#", class: 'text-decoration-none text-muted pe-none' %>
          <% else %>
            <%= link_to alibi.title, alibi_path(alibi) %>
          <% end %>

        </div>
        <div class="notification-actions">
          <div class="d-flex gap-3">
            <span class="badge bg-primary fw-normal"><%= alibi.category.capitalize %></span>
            <span class="badge bg-warning fw-normal"><%= alibi.price %>€</span>
            <span class="badge bg-secondary fw-normal"><%= alibi.status %></span>
          </div>
        </div>
      </div>
    <% end %>
    </ul>
  </div>

  <div class='my-3'>
    <h2>Bookings from other users on my alibis</h2>
    <% @alibis.joins(:bookings).where(status: :available).distinct.reverse.each do |alibi| %>
      <ul class="list-group mb-1">
        <h4><%= alibi.title %></h4>
        <% alibi.bookings.reverse.each do |booking| %>
          <div class="notification">
            <% avatar = (booking.user.photo.attached? ? booking.user.photo : 'avatar.png') %>
            <%= image_tag avatar, class: "avatar-large me-3" %>
            <div class="notification-content">
              <p><small><%= booking.created_at.strftime("%Y/%m/%d - %H:%M") %></small></p>
              <p><%= booking.user.email %></p>
            </div>

            <div class="notification-actions">
              <div class="d-flex gap-3">
                <% case %>
                  <% when booking.pending? %>
                    <%= button_to 'Accept', accept_booking_path(booking), method: :patch, class: 'btn btn-outline-success' %>
                    <%= button_to 'Decline', decline_booking_path(booking), method: :patch, class: 'btn btn-outline-danger' %>
                  <% when booking.approved? %>
                    <button class='btn btn-success disabled'>Accepted</button>
                    <%= button_to 'Cancel', cancel_booking_path(booking), method: :patch, class: 'btn btn-outline-dark' %>
                  <% when booking.declined? %>
                    <button class='btn btn-danger disabled'>Declined</button>
                  <% when booking.cancelled? %>
                    <button class='btn btn-dark disabled'>Cancelled</button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class='my-3'>
    <h2>My bookings</h2>
    <ul class="list-group">
    <% if @bookings.empty? %>
      <p>You booked nothing yet!</p>
    <% else %>
      <% @bookings.reverse.each do |booking| %>
        <div class="notification">
          <div class="notification-content">
            <p><small><%= booking.created_at.strftime("%Y/%m/%d - %H:%M") %></small></p>
            <% if booking.alibi.archived? %>
              <%= link_to booking.alibi.title, "#", class: 'text-decoration-none text-muted pe-none' %>
            <% else %>
              <%= link_to booking.alibi.title, alibi_path(booking.alibi) %>
            <% end %>
            <div class="d-flex gap-1 mt-1">
              <span class="badge bg-primary fw-normal"><%= booking.alibi.category.capitalize %></span>
              <span class="badge bg-warning fw-normal"><%= booking.alibi.price %>€</span>
              <span class="badge bg-secondary fw-normal"><%= booking.alibi.status %></span>
            </div>
          </div>

          <div class="notification-actions">
            <div class="d-flex gap-3">
              <% case %>
                <% when booking.pending? %>
                  <span class='badge bg-dark fw-normal'>Pending</span>
                <% when booking.approved? %>
                  <span class='badge bg-success fw-normal'>Accepted</span>
                <% when booking.declined? %>
                  <span class='badge bg-danger fw-normal'>Declined</span>
                <% when booking.cancelled? %>
                  <span class='badge bg-secondary fw-normal'>Cancelled</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(https://www.femmaufoyer.net/wp-content/uploads/2022/07/reunion-de-famille-0.jpg);">
  <div class="">
    <h1 class="text-center align-middle vertical-align">An App where you can find your perfect alibi!</h1>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: alibis_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "What kind of alibi do you need ?"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <h2 class="text-center my-5">An App for Alibis</h2>

  <div class="cartes row text-center d-flex justify-content-center flex-wrap">
    <div class="categories m-2 col">
      <%= image_tag("date.jpg", class: "card-img-top rounded-top-2", alt: "...") %>
      <div class="color rounded-bottom p-3 mb-2 bg-dark text-white h-auto">
        <h5 class="card-title">Alibi for dates</h5>
        <p class="card-text">If you want to fake date with someone...</p>
        <div>
          <a href="/alibis?query=date" class="btn btn-outline-secondary">Date</a>
        </div>
      </div>
    </div>
    <div class="categories m-2 col">
      <%= image_tag("cinema.jpg", class: "card-img-top rounded-top-2", alt: "...") %>
      <div class="color rounded-bottom p-3 mb-2 bg-dark text-white h-auto">
        <h5 class="card-title">Alibi for cinema</h5>
        <p class="card-text">If you want to go see a movie with someone...</p>
        <div>
          <a href="/alibis?query=cinema" class="btn btn-outline-secondary">Cinema</a>
        </div>
      </div>
    </div>
    <div class="categories m-2 col">
      <%= image_tag("journey.jpg", class: "card-img-top rounded-top-2", alt: "...") %>
      <div class="color rounded-bottom p-3 mb-2 bg-dark text-white h-auto">
        <h5 class="card-title">Alibi for journey</h5>
        <p class="card-text">If you want to go in a journey with someone...</p>
        <div>
          <a href="/alibis?query=journey" class="btn btn-outline-secondary">Journey</a>
        </div>
      </div>
    </div>
    <div class="categories m-2 col">
      <%= image_tag("speak.jpg", class: "card-img-top rounded-top-2", alt: "...") %>
      <div class="color rounded-bottom p-3 mb-2 bg-dark text-white h-auto">
        <h5 class="card-title">Alibi to talk to</h5>
        <p class="card-text">If you want to talk with someone in a café...</p>
        <div>
          <a href="/alibis?query=speak" class="btn btn-outline-secondary">Speak</a>
        </div>
      </div>
    </div>
    <div class="categories m-2 col">
      <%= image_tag("family.jpg", class: "card-img-top rounded-top-2", alt: "...") %>
      <div class="color rounded-bottom p-3 mb-2 bg-dark text-white h-auto">
        <h5 class="card-title">Alibi for family</h5>
        <p class="card-text">If you need a fake companion to present...</p>
        <div>
          <a href="/alibis?query=family" class="btn btn-outline-secondary">Family</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logoAlibi.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "All alibis", alibis_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Create an Alibi", new_alibi_path, class: "btn btn-outline-primary mx-3" %>
          </li>
          <li class="dropdown">
            <% avatar = (current_user.photo.attached? ? current_user.photo : "avatar.png") %>
            <%= image_tag avatar, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Edit my profile", edit_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Show</h1>

<p><%= @user.inspect %></p>